services:
  - type: web
    name: backend-api
    env: docker
    plan: free
    # Dockerfile at repo root will be used to build the container
    envVars:
      - key: DATABASE_URL
        scope: run
      - key: DB_USERNAME
        scope: run
      - key: DB_PASSWORD
        scope: run
        isPrivate: true
      - key: SPRING_PROFILES_ACTIVE
        value: prod
